services:
  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  auth_db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${AUTH_DB_USER}
      - POSTGRES_PASSWORD=${AUTH_DB_PASSWORD}
      - POSTGRES_DB=${AUTH_DB_NAME}
    volumes:
      - auth_pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${AUTH_DB_USER} -d $${AUTH_DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build: ./api
    ports:
      - "8080:8080"
    volumes:
      - ./api:/app
    working_dir: /app
    command: go run ./cmd/main.go
    depends_on:
      db:
        condition: service_healthy
      data_server:
        condition: service_started
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}

  auth_server:
    build: ./auth_server
    ports:
      - "4000:4000"
    volumes:
      - ./auth_server:/app
    working_dir: /app
    depends_on:
      auth_db:
        condition: service_healthy
    restart: always
    env_file:
      - .env
    environment:
      - DATABASE_URL=${AUTH_DATABASE_URL}

  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - VITE_BLOCKCHAIN_NETWORK=${VITE_BLOCKCHAIN_NETWORK}
      - VITE_BLOCKCHAIN_WC_PROJECT_ID=${VITE_BLOCKCHAIN_WC_PROJECT_ID}
      - VITE_BLOCKCHAIN_RPC=${VITE_BLOCKCHAIN_RPC}
      - VITE_SEPOLIA_RPC=${VITE_SEPOLIA_RPC}
      - VITE_BLOCKCHAIN_CONTRACT_BUCKET_ANCHOR=${VITE_BLOCKCHAIN_CONTRACT_BUCKET_ANCHOR}
    ports:
      - "5173:5173"
    volumes:
      - ./webapp:/app
    working_dir: /app
    command: yarn dev
    depends_on:
      api:
        condition: service_started
      eth_local:
        condition: service_healthy
  
  data_server:
    build: ./data_server
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - GRPC_ADDR=:9090
    depends_on:
      db:
        condition: service_healthy
    expose:
      - "9090"

  ledger:
    build: ./ledger
    ports: ["9091:9091"]
    env_file: [.env]
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DATASERVER_GRPC_ADDR=data_server:9090 
      - GITHUB_WEBHOOK_SECRET=${GITHUB_WEBHOOK_SECRET}
    depends_on:
      api:
        condition: service_started
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:9091/healthz || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5

  eth_local:
    image: ghcr.io/foundry-rs/foundry:stable
    network_mode: "host"             # ← use host network
    command: ["anvil","--host","127.0.0.1","--port","8545","--chain-id","31337","--block-time","1","--base-fee","0","--gas-price","0"]
    # no `ports:` with host networking
    healthcheck:
      test: ["CMD","cast","rpc","eth_chainId","--rpc-url","http://127.0.0.1:8545"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 5s

  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    depends_on:
      - ledger
    command: tunnel --url http://ledger:9091

volumes:
  pgdata:
  auth_pgdata:


